repository:
  name: certfwd
  description: A certificate-aware reverse proxy for HTTPS debugging
  homepage: https://github.com/bemafred/certfwd
  default_branch: main
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true

branches:
  - name: main
    protection:
      required_status_checks:
        strict: false
        contexts:
          - "build (certfwd-cross-platform.yml)"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: false
      restrictions: null
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false

# This file can be used with Probot Settings or GitHub CLI automation
